//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarSystemConsumption.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsInstalled
    {
        public int Id { get; set; }
        public Nullable<int> SchoolNo { get; set; }
        public Nullable<int> ItemNo { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<bool> ForClass { get; set; }
        public Nullable<bool> ForOffice { get; set; }
        public Nullable<bool> ForKafteria { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual School School { get; set; }
    }
}
