//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarSystemConsumption.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public School()
        {
            this.ItemsInstalleds = new HashSet<ItemsInstalled>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ClassesCount { get; set; }
        public Nullable<int> OfficeseCount { get; set; }
        public Nullable<int> KafteriaCount { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsInstalled> ItemsInstalleds { get; set; }
    }
}
